"""
Fitness Plan Model
SQLAlchemy ORM model for fitness plans generated by AI
"""

from sqlalchemy import Column, String, DateTime, Text, Boolean, Integer, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime
import uuid
from models.base import Base


class Plan(Base):
    """
    Fitness plan model
    TODO: Implement plan with AI-generated workouts and progress tracking
    """
    __tablename__ = "plans"

    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)

    # Plan details
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    goal = Column(String, nullable=False)  # e.g., "weight_loss", "muscle_gain"
    duration_days = Column(Integer, nullable=True)

    # Plan content
    workout_schedule = Column(Text, nullable=False)  # JSON string of workouts
    nutrition_guidelines = Column(Text, nullable=True)  # JSON string of nutrition info
    ai_model_used = Column(String, nullable=True)  # e.g., "gemini", "groq"

    # Plan status
    is_active = Column(Boolean, default=False)
    is_completed = Column(Boolean, default=False)
    progress_percentage = Column(Integer, default=0)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<Plan(id={self.id}, user_id={self.user_id}, name={self.name})>"
